#ifndef _VERSION_H
#define _VERSION_H

#define PROJECT_NAME "RVDataFusionServer"
#define PROJECT_VERSION "0.2.0"
/* #undef PROJECT_VERSION_MAJOR */
#define PROJECT_VERSION_MINOR "2"
/* #undef PROJECT_VERSION_PATCH */
#define VERSION_BUILD_TIME "0.2.0_20230228_09.19.10"

#endif //_VERSION_H
