#ifndef _VERSION_H
#define _VERSION_H

#define PROJECT_NAME "RVDataFusionServer"
#define PROJECT_VERSION "0.0.4"
/* #undef PROJECT_VERSION_MAJOR */
/* #undef PROJECT_VERSION_MINOR */
#define PROJECT_VERSION_PATCH "4"
#define VERSION_BUILD_TIME "0.0.4_20230120_11.45.24"

#endif //_VERSION_H
