#ifndef _VERSION_H
#define _VERSION_H

#define PROJECT_NAME "RVDataFusionServer"
#define PROJECT_VERSION "2.3.2"
#define PROJECT_VERSION_MAJOR "2"
#define PROJECT_VERSION_MINOR "3"
#define PROJECT_VERSION_PATCH "2"
#define VERSION_BUILD_TIME "2.3.2_20230625_09.20.27"

#endif //_VERSION_H
